FROM gooshan/ubuntu-dev:latest

RUN apt-get update \
  && apt-get upgrade -y 
  
RUN apt-get install -y --force-yes  \
  flex libaa1-dev iso-codes libgtk-3-dev \
  libasound2-dev libvorbis-dev libshout3-dev libflac-dev libdca-dev \
  libfaad-dev libmpcdec-dev libopus-dev libslv2-dev libsndfile1-dev \
  libsoundtouch-dev libmad0-dev libmp3lame-dev libmpeg2-4-dev \
  libxt-dev libtheora-dev libv4l-dev libavcodec-dev libavformat-dev libdv4-dev libwavpack-dev libvpx-dev \
  libschroedinger-dev libiec61883-dev libspeex-dev libmimic-dev libx264-dev libxvidcore-dev liba52-0.7.4-dev \
  libpng-dev libtiff5-dev libjasper-dev libjpeg-dev   \
  libtag1-dev libexif-dev libiptcdata0-dev \
  librtmp-dev python3-dev autopoint libva-dev
  
# visual
#  libcairo2-dev libvisual-0.4-dev libcaca-dev libpango1.0-dev  gtk-doc-tools \
#  libass-dev libexempi-dev librsvg2-dev libx11-dev libsidplay1-dev \
#
# text
#  libraw1394-dev libavc1394-dev libdc1394-22-dev \
#  libpulse-dev libcdaudio-dev libcdio-dev libdvdnav-dev libdvdread-dev \
#  libzbar-dev libzvbi-dev libopencore-amrnb-dev libopencore-amrwb-dev \
#  ladspa-sdk libgsm1-dev libgme-dev libkate-dev libmodplug-dev libofa0-dev libspandsp-dev \
#  libmms-dev

RUN apt-get clean 

ENV LD_LIBRARY_PATH /usr/local/lib/
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig/:/usr/include/pygobject-3.0/:/root/sources/gstreamer/gstreamer/pkgconfig/
  
VOLUME /root/sources
ADD sources /root/sources
WORKDIR /root/sources/gstreamer

RUN ./autogen.sh --disable-gtk-doc && \
  make -j$(nproc) && \
  make install

WORKDIR /root/sources/gst-plugins-base
RUN ./autogen.sh --disable-gtk-doc && \
  make -j$(nproc) && \
  make install

WORKDIR /root/sources/gst-plugins-good
RUN ./autogen.sh --disable-gtk-doc && \
  make -j$(nproc) && \
  make install

WORKDIR /root/sources/gst-plugins-ugly
RUN ./autogen.sh --disable-gtk-doc && \
  make -j$(nproc) && \
  make install

WORKDIR /root/sources/gst-libav
RUN ./autogen.sh --disable-gtk-doc && \
  make -j$(nproc) && \
  make install

WORKDIR /root/sources/gst-plugins-bad
RUN ./autogen.sh --disable-gtk-doc --with-opengl=yes && \
  make -j$(nproc) CFLAGS+="-Wno-error -Wno-redundant-decls" CXXFLAGS+="-Wno-redundant-decls" && \
  make install

WORKDIR /root/sources/gst-python
RUN ./configure --disable-gtk-doc && \
  make -j$(nproc) && \
  make install

WORKDIR /root/sources/gst-omx
RUN ./autogen.sh --disable-gtk-doc --with-omx-target=bellagio && \
  make -j$(nproc) CFLAGS+="-Wno-error -Wno-redundant-decls" && \
  make install

WORKDIR /root/sources/gstreamer-vaapi
RUN ./autogen.sh --disable-gtk-doc --with-omx-target=bellagio && \
  make -j$(nproc) CFLAGS+="-Wno-error -Wno-redundant-decls" && \
  make install

WORKDIR /root





